"""add optional flag to meal ingredients

Revision ID: 01a455a20bba
Revises: 05999f6a2ec2
Create Date: 2026-08-15 16:49:16.923314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a455a20bba'
down_revision: Union[str, Sequence[str], None] = '05999f6a2ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "meal_ingredients",
        sa.Column(
            "is_optional",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.alter_column(
        "meal_ingredients",
        "is_optional",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_ingredients', 'is_optional')
    # ### end Alembic commands ###
