"""replace age with date_of_birth

Revision ID: 034eb0b81e72
Revises: ca28b1a5c611
Create Date: 2026-08-04 22:39:41.564039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034eb0b81e72'
down_revision: Union[str, Sequence[str], None] = 'ca28b1a5c611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.drop_column('profiles', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###
