"""create disliked ingredients table

Revision ID: 0f49b1902a25
Revises: a1d31c3b510f
Create Date: 2026-08-04 23:07:18.174799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f49b1902a25'
down_revision: Union[str, Sequence[str], None] = 'a1d31c3b510f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disliked_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disliked_ingredients_profile_id'), 'disliked_ingredients', ['profile_id'], unique=False)
    op.drop_constraint(op.f('profiles_id_key'), 'profiles', type_='unique')
    op.drop_column('profiles', 'disliked_ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('disliked_ingredients', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('profiles_id_key'), 'profiles', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_disliked_ingredients_profile_id'), table_name='disliked_ingredients')
    op.drop_table('disliked_ingredients')
    # ### end Alembic commands ###
