"""create favorites table

Revision ID: 2e7b4adc1b5d
Revises: 31b00c8d3565
Create Date: 2026-08-19 14:44:54.291565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7b4adc1b5d'
down_revision: Union[str, Sequence[str], None] = '31b00c8d3565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'meal_id', name='uq_favorites_profile_meal')
    )
    op.create_index(op.f('ix_favorites_meal_id'), 'favorites', ['meal_id'], unique=False)
    op.create_index(op.f('ix_favorites_profile_id'), 'favorites', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_profile_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_meal_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
