"""create meal plan entries

Revision ID: 31b00c8d3565
Revises: 80b9d0d7cf89
Create Date: 2026-08-18 12:47:56.445929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b00c8d3565'
down_revision: Union[str, Sequence[str], None] = '80b9d0d7cf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('meal_slot', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_entries_meal_id'), 'meal_plan_entries', ['meal_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_planned_date'), 'meal_plan_entries', ['planned_date'], unique=False)
    op.create_index('ix_meal_plan_entries_profile_date', 'meal_plan_entries', ['profile_id', 'planned_date'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_profile_id'), 'meal_plan_entries', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plan_entries_profile_id'), table_name='meal_plan_entries')
    op.drop_index('ix_meal_plan_entries_profile_date', table_name='meal_plan_entries')
    op.drop_index(op.f('ix_meal_plan_entries_planned_date'), table_name='meal_plan_entries')
    op.drop_index(op.f('ix_meal_plan_entries_meal_id'), table_name='meal_plan_entries')
    op.drop_table('meal_plan_entries')
    # ### end Alembic commands ###
