"""create food allergies table

Revision ID: a1d31c3b510f
Revises: 034eb0b81e72
Create Date: 2026-08-04 23:01:09.434384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d31c3b510f'
down_revision: Union[str, Sequence[str], None] = '034eb0b81e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_allergies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('allergy', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_food_allergies_profile_id'), 'food_allergies', ['profile_id'], unique=False)
    op.drop_column('profiles', 'food_allergies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('food_allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_food_allergies_profile_id'), table_name='food_allergies')
    op.drop_table('food_allergies')
    # ### end Alembic commands ###
