"""create ingredient substitutions

Revision ID: acc64e062c88
Revises: 01a455a20bba
Create Date: 2026-08-15 17:09:50.208223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc64e062c88'
down_revision: Union[str, Sequence[str], None] = '01a455a20bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_substitutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredient', sa.String(length=100), nullable=False),
    sa.Column('substitute', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_substitutions_ingredient'), 'ingredient_substitutions', ['ingredient'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_substitutions_ingredient'), table_name='ingredient_substitutions')
    op.drop_table('ingredient_substitutions')
    # ### end Alembic commands ###
