"""add profile_image_url to profiles

Revision ID: ca28b1a5c611
Revises: f2e61d0eadf3
Create Date: 2026-08-04 13:58:39.493883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca28b1a5c611'
down_revision: Union[str, Sequence[str], None] = 'f2e61d0eadf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('profiles_auth_id_unique'), 'profiles', type_='unique')
    op.create_unique_constraint(None, 'profiles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.create_unique_constraint(op.f('profiles_auth_id_unique'), 'profiles', ['auth_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
