"""fix daily budget column name

Revision ID: f2e61d0eadf3
Revises: 06f8e32c3eed
Create Date: 2026-08-04 10:54:56.149780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e61d0eadf3'
down_revision: Union[str, Sequence[str], None] = '06f8e32c3eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('daily_budget', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['id'])
    op.drop_column('profiles', 'daily_bugdet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('daily_bugdet', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'daily_budget')
    # ### end Alembic commands ###
